# Generated by Django 5.0 on 2024-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_to_translate", models.TextField()),
                ("source_lang", models.CharField(max_length=10)),
                ("target_lang", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
            ],
        ),
    ]
